#!/usr/bin/env bash
set -euo pipefail

PHASE7_TOPICS=(
  "dr.p7.normal|6|1200|delete"
  "dr.p7.state|4|900|compact"
  "dr.p7.groups|6|1000|delete"
  "dr.p7.txn|4|500|transactional"
)

PHASE7_SCENARIOS=(
  "hard-stop"
  "skewed-stop-copy"
  "isr-skew"
)

PHASE7_NORMAL_TOPIC="dr.p7.normal"
PHASE7_STATE_TOPIC="dr.p7.state"
PHASE7_GROUPS_TOPIC="dr.p7.groups"
PHASE7_TXN_TOPIC="dr.p7.txn"

PHASE7_FULL_GROUP="${PHASE7_FULL_GROUP:-dr.phase7.group.full}"
PHASE7_PARTIAL_GROUP="${PHASE7_PARTIAL_GROUP:-dr.phase7.group.partial}"
PHASE7_PARTIAL_INITIAL_MESSAGES="${PHASE7_PARTIAL_INITIAL_MESSAGES:-260}"

PHASE7_SKEW_SECONDS_1="${PHASE7_SKEW_SECONDS_1:-12}"
PHASE7_SKEW_SECONDS_2="${PHASE7_SKEW_SECONDS_2:-12}"

PHASE7_TXID_COMMITTED="${PHASE7_TXID_COMMITTED:-dr-phase7-tx-committed}"
PHASE7_TXID_ABORTED="${PHASE7_TXID_ABORTED:-dr-phase7-tx-aborted}"
PHASE7_TXID_HANGING="${PHASE7_TXID_HANGING:-dr-phase7-tx-hanging}"

PHASE7_TXN_COMMITTED_RECORDS="${PHASE7_TXN_COMMITTED_RECORDS:-500}"
PHASE7_TXN_ABORT_RUN_SECONDS="${PHASE7_TXN_ABORT_RUN_SECONDS:-8}"
PHASE7_TXN_HANG_RUN_SECONDS="${PHASE7_TXN_HANG_RUN_SECONDS:-8}"
PHASE7_TXN_ABORT_DURATION_MS="${PHASE7_TXN_ABORT_DURATION_MS:-600000}"
PHASE7_TXN_HANG_DURATION_MS="${PHASE7_TXN_HANG_DURATION_MS:-600000}"

PHASE7_BG_RUN_SECONDS="${PHASE7_BG_RUN_SECONDS:-180}"
PHASE7_BG_THROUGHPUT="${PHASE7_BG_THROUGHPUT:-200}"
PHASE7_BG_NUM_RECORDS="${PHASE7_BG_NUM_RECORDS:-200000}"
PHASE7_BG_TXID="${PHASE7_BG_TXID:-dr-phase7-live-tx}"
PHASE7_BG_TX_DURATION_MS="${PHASE7_BG_TX_DURATION_MS:-120000}"

PHASE7_SMOKE_TOPIC="${PHASE7_SMOKE_TOPIC:-dr.p7.normal}"
PHASE7_SMOKE_MESSAGES="${PHASE7_SMOKE_MESSAGES:-40}"
PHASE7_SMOKE_CONSUME="${PHASE7_SMOKE_CONSUME:-20}"
