#!/usr/bin/env bash
set -euo pipefail

PHASE5_FULL_TOPIC="dr.p5.txn.full"
PHASE5_PARTIAL_TOPIC="dr.p5.txn.partial"
PHASE5_ABORTED_TOPIC="dr.p5.txn.aborted"
PHASE5_HANGING_TOPIC="dr.p5.txn.hanging"

PHASE5_TOPIC_SPECS=(
  "${PHASE5_FULL_TOPIC}|4"
  "${PHASE5_PARTIAL_TOPIC}|4"
  "${PHASE5_ABORTED_TOPIC}|4"
  "${PHASE5_HANGING_TOPIC}|4"
)

PHASE5_FULL_GROUP="${PHASE5_FULL_GROUP:-dr.phase5.group.full}"
PHASE5_PARTIAL_GROUP="${PHASE5_PARTIAL_GROUP:-dr.phase5.group.partial}"

PHASE5_FULL_COMMITTED_RECORDS="${PHASE5_FULL_COMMITTED_RECORDS:-600}"
PHASE5_PARTIAL_COMMITTED_RECORDS="${PHASE5_PARTIAL_COMMITTED_RECORDS:-700}"
PHASE5_PARTIAL_INITIAL_MESSAGES="${PHASE5_PARTIAL_INITIAL_MESSAGES:-250}"
PHASE5_PARTIAL_RESUME_MESSAGES="${PHASE5_PARTIAL_RESUME_MESSAGES:-120}"

PHASE5_ABORT_RUN_SECONDS="${PHASE5_ABORT_RUN_SECONDS:-8}"
PHASE5_HANG_RUN_SECONDS="${PHASE5_HANG_RUN_SECONDS:-8}"
PHASE5_ABORT_HANG_THROUGHPUT="${PHASE5_ABORT_HANG_THROUGHPUT:-120}"
PHASE5_ABORT_HANG_MAX_RECORDS="${PHASE5_ABORT_HANG_MAX_RECORDS:-200000}"
PHASE5_LONG_TX_DURATION_MS="${PHASE5_LONG_TX_DURATION_MS:-600000}"

PHASE5_TXID_FULL="${PHASE5_TXID_FULL:-dr-phase5-tx-full}"
PHASE5_TXID_PARTIAL="${PHASE5_TXID_PARTIAL:-dr-phase5-tx-partial}"
PHASE5_TXID_ABORTED="${PHASE5_TXID_ABORTED:-dr-phase5-tx-aborted}"
PHASE5_TXID_HANGING="${PHASE5_TXID_HANGING:-dr-phase5-tx-hanging}"
