#!/usr/bin/env bash
set -euo pipefail

PHASE7B_SCENARIOS=(
  "loss-acks1-unclean-target"
  "loss-live-copy-flush-window"
)

PHASE7B_CHAOS_TOPIC="${PHASE7B_CHAOS_TOPIC:-dr.p7b.chaos.loss}"
PHASE7B_CHAOS_PARTITION="${PHASE7B_CHAOS_PARTITION:-0}"
PHASE7B_CHAOS_REPLICA_ASSIGNMENT="${PHASE7B_CHAOS_REPLICA_ASSIGNMENT:-1:2:3}"

PHASE7B_ACKS1_MAX_MESSAGES="${PHASE7B_ACKS1_MAX_MESSAGES:-5000}"
PHASE7B_ACKS1_THROUGHPUT="${PHASE7B_ACKS1_THROUGHPUT:-500}"
PHASE7B_ACKS1_PRODUCE_SECONDS="${PHASE7B_ACKS1_PRODUCE_SECONDS:-30}"
PHASE7B_ACKS_ALL_THROUGHPUT="${PHASE7B_ACKS_ALL_THROUGHPUT:-500}"
PHASE7B_LIVE_PRODUCE_SECONDS="${PHASE7B_LIVE_PRODUCE_SECONDS:-18}"
PHASE7B_LIVE_COPY_START_DELAY_SECONDS="${PHASE7B_LIVE_COPY_START_DELAY_SECONDS:-4}"

PHASE7B_SKEW_SECONDS_1="${PHASE7B_SKEW_SECONDS_1:-10}"
PHASE7B_SKEW_SECONDS_2="${PHASE7B_SKEW_SECONDS_2:-10}"
PHASE7B_ITERATIONS="${PHASE7B_ITERATIONS:-10}"

PHASE7B_ACCEPT_NONZERO_BOUNDED="${PHASE7B_ACCEPT_NONZERO_BOUNDED:-true}"
PHASE7B_ABORT_IF_ALL_LOST="${PHASE7B_ABORT_IF_ALL_LOST:-true}"
