#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"
# shellcheck source=phase9_scenarios.sh
source "${SCRIPT_DIR}/phase9_scenarios.sh"

SCENARIO="${1:-new-identity-direct-import}"
SNAPSHOT_ID="${2:-phase9-${SCENARIO}-$(timestamp_utc)}"
SNAPSHOT_DIR="${ROOT_DIR}/artifacts/snapshots/${SNAPSHOT_ID}"
LATEST_DIR="${ROOT_DIR}/artifacts/latest"
SOURCE_RUNTIME_ENV="${LATEST_DIR}/source/phase9/runtime/phase9_runtime.env"
TARGET_SCENARIO_DIR="${LATEST_DIR}/target/phase9/${SCENARIO}"
MUTATION_ENV_FILE="${TARGET_SCENARIO_DIR}/mutation.env"
mkdir -p "${SNAPSHOT_DIR}/source-data" "${LATEST_DIR}" "${TARGET_SCENARIO_DIR}"

is_valid=0
for expected in "${PHASE9_SCENARIOS[@]}"; do
  if [[ "${SCENARIO}" == "${expected}" ]]; then
    is_valid=1
    break
  fi
done
if [[ "${is_valid}" -ne 1 ]]; then
  echo "Unknown phase9 scenario '${SCENARIO}'. Valid: ${PHASE9_SCENARIOS[*]}" >&2
  exit 1
fi

if [[ ! -f "${SOURCE_RUNTIME_ENV}" ]]; then
  echo "Missing source runtime env: ${SOURCE_RUNTIME_ENV}" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${SOURCE_RUNTIME_ENV}"

for broker in 1 2 3; do
  ensure_broker_data_present "${ROOT_DIR}/data/source" "${broker}"
done

compose_cmd stop "${TARGET_SCHEMA_SERVICE}" >/dev/null 2>&1 || true
compose_cmd stop "${SOURCE_SCHEMA_SERVICE}" >/dev/null 2>&1 || true
compose_cmd stop "${TARGET_SERVICES[@]}" >/dev/null 2>&1 || true
# Use SIGKILL (compose kill) rather than graceful stop (compose stop) for source brokers.
# compose stop sends SIGTERM → starts KRaft controlled-shutdown → the controller removes
# each broker from ISR partitions as they acknowledge shutdown → with all 3 stopping
# simultaneously this can drain _confluent-command-0 (and other internal topics) to
# empty ISR before SIGKILL arrives 10 s later.  An empty ISR means no leader can be
# elected on the target (unclean election is disabled), causing every broker's Confluent
# license validator to time out (60 s) and crash-loop indefinitely.
# With SIGKILL the KRaft metadata log records the fully-running state (ISR={1,2,3} for
# all partitions).  On target restart the preferred leader (broker-3 for
# _confluent-command-0) wins leadership quickly, and all brokers can validate their
# license without the circular dependency that causes the crash loop.
compose_cmd kill "${SOURCE_SERVICES[@]}" >/dev/null 2>&1 || true

rsync -a --delete "${ROOT_DIR}/data/source/" "${SNAPSHOT_DIR}/source-data/"
rsync -a --delete "${SNAPSHOT_DIR}/source-data/" "${ROOT_DIR}/data/target/"

for broker in 1 2 3; do
  ensure_broker_data_present "${ROOT_DIR}/data/target" "${broker}"
done

toggle_cluster_id() {
  local current="$1"
  local first="${current:0:1}"
  local rest="${current:1}"
  if [[ "${first}" == "A" ]]; then
    printf "B%s\n" "${rest}"
  else
    printf "A%s\n" "${rest}"
  fi
}

source_cluster_id_from_data="$(grep '^cluster.id=' "${ROOT_DIR}/data/target/broker1/meta.properties" | cut -d= -f2)"

if [[ "${SCENARIO}" == "new-identity-reachable-allowed" ]]; then
  # Faithful restore: the rsync'd copy is fully consistent — meta.properties, KRaft metadata
  # log (ClusterRecord), and topic partition data all carry the source cluster.id.
  # No mutation is needed. The broker starts normally and all data is immediately accessible.
  # This scenario proves that a correctly-performed restore (preserving cluster identity) works.
  target_new_cluster_id="${source_cluster_id_from_data}"
else
  # new-identity-direct-import: delete meta.properties and the KRaft metadata log so the
  # Confluent image formats the cluster fresh from TARGET_CLUSTER_ID on first boot.
  # User partition directories are left in place; their partition.metadata UUIDs were
  # generated by the source cluster and will not match the freshly-registered KRaft UUIDs.
  # Kafka renames those directories to <dir>-stray (§4.13 behaviour), making the source
  # topic data inaccessible on the new cluster.
  target_new_cluster_id="$(toggle_cluster_id "${source_cluster_id_from_data}")"
  for broker in 1 2 3; do
    rm -f "${ROOT_DIR}/data/target/broker${broker}/meta.properties"
    rm -rf "${ROOT_DIR}/data/target/broker${broker}/__cluster_metadata-0"
  done
fi

upsert_runtime_var "TARGET_CLUSTER_ID" "${target_new_cluster_id}"

cat > "${MUTATION_ENV_FILE}" <<EOF
scenario=${SCENARIO}
phase9_source_cluster_id=${source_cluster_id}
phase9_original_target_cluster_id=${source_cluster_id_from_data}
phase9_target_cluster_id=${target_new_cluster_id}
phase9_topic=${source_topic}
phase9_source_end_sum=${source_end_sum}
EOF

echo "${SNAPSHOT_ID}" > "${LATEST_DIR}/snapshot_id.txt"
echo "${SCENARIO}" > "${LATEST_DIR}/phase9_scenario.txt"
echo "Phase9 snapshot ${SNAPSHOT_ID} (${SCENARIO}) prepared: target_cluster_id=${target_new_cluster_id}."
